### ISSUE TITLE
[iOS parallel execution]: problems about the start of two or more WDA instances

### ISSUE THREAD

**Issue by rtardi** [facebook/WebDriverAgent#1007]
I'm opening in parallel two or more instances of the WDA, with appium, to execute some tests on more iOS and/or Android devices.
I have a problem during the execution in this context: one WDA instance generates an error (for both android or iOS environment).
Now, I'm using real 2 iPhone and 1 iPad but **SOMETIMES** (random), not always, I have the following error during the creation of the connections to device on the at least _one_:

```
018-10-04 14:34:22:430 - info: [Appium] Welcome to Appium v1.9.1
2018-10-04 14:34:22:433 - info: [Appium] Non-default server args:
2018-10-04 14:34:22:434 - info: [Appium]   address: 127.0.0.1
2018-10-04 14:34:22:435 - info: [Appium]   port: 15276
2018-10-04 14:34:22:435 - info: [Appium]   bootstrapPort: 57059
2018-10-04 14:34:22:435 - info: [Appium]   sessionOverride: true
2018-10-04 14:34:22:435 - info: [Appium]   log: /Users/raffaele/Develop/Beaver/MobileActuator/logs/c6777294aefb1b537a93499cb24b90158f87b8a8_it.k.Beaver_2018-10-04-16:34:19.663.log
2018-10-04 14:34:22:435 - info: [Appium]   webkitDebugProxyPort: 57061
2018-10-04 14:34:22:435 - info: [Appium]   wdaLocalPort: 57060
2018-10-04 14:34:22:476 - info: [Appium] Appium REST http interface listener started on 127.0.0.1:15276
2018-10-04 14:34:22:607 - info: [HTTP] --> GET /wd/hub/status
2018-10-04 14:34:22:607 - info: [HTTP] {}
2018-10-04 14:34:22:611 - info: [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2018-10-04 14:34:22:614 - info: [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1"}}
2018-10-04 14:34:22:621 - info: [HTTP] <-- GET /wd/hub/status 200 11 ms - 67
2018-10-04 14:34:22:621 - info: [HTTP] 
2018-10-04 14:34:22:710 - info: [Appium] Received SIGTERM - shutting down
2018-10-04 14:34:22:875 - _error: uncaughtException: write EPIPE date=Thu Oct 04 2018 16:34:22 GMT+0200 (CEST), pid=56184, uid=501, gid=20, cwd=/Users/raffaele/Develop/Beaver/MobileActuator, execPath=/usr/local/bin/node, version=v8.11.1, argv=[/usr/local/bin/node, /usr/local/bin/appium, --port, 15276, --address, 127.0.0.1, --log, /Users/raffaele/Develop/Beaver/MobileActuator/logs/c6777294aefb1b537a93499cb24b90158f87b8a8_it.k.Beaver_2018-10-04-16:34:19.663.log, --bootstrap-port, 57059, --webkit-debug-proxy-port, 57061, --session-override, --webdriveragent-port, 57060], rss=138133504, heapTotal=109203456, heapUsed=82299192, external=371155, loadavg=[6.2041015625, 6.3583984375, 6.6787109375], uptime=270598, trace=[column=11, file=util.js, function=_errnoException, line=1022, method=null, native=false, column=14, file=net.js, function=WriteWrap.afterWrite, line=880, method=afterWrite, native=false], stack=[Error: write EPIPE,     at _errnoException (util.js:1022:11),     at WriteWrap.afterWrite (net.js:880:14)]
2018-10-04 14:34:22:884 - error: uncaughtException: write EPIPE date=Thu Oct 04 2018 16:34:22 GMT+0200 (CEST), pid=56184, uid=501, gid=20, cwd=/Users/raffaele/Develop/Beaver/MobileActuator, execPath=/usr/local/bin/node, version=v8.11.1, argv=[/usr/local/bin/node, /usr/local/bin/appium, --port, 15276, --address, 127.0.0.1, --log, /Users/raffaele/Develop/Beaver/MobileActuator/logs/c6777294aefb1b537a93499cb24b90158f87b8a8_it.k.Beaver_2018-10-04-16:34:19.663.log, --bootstrap-port, 57059, --webkit-debug-proxy-port, 57061, --session-override, --webdriveragent-port, 57060], rss=138477568, heapTotal=109203456, heapUsed=82474248, external=375275, loadavg=[6.2041015625, 6.3583984375, 6.6787109375], uptime=270598, trace=[column=11, file=util.js, function=_errnoException, line=1022, method=null, native=false, column=14, file=net.js, function=WriteWrap.afterWrite, line=880, method=afterWrite, native=false], stack=[Error: write EPIPE,     at _errnoException (util.js:1022:11),     at WriteWrap.afterWrite (net.js:880:14)]
```
al long as the other executions don't generate errors.

Is there anyone to help me to understand or explain me the solution?

P.S.: I started the appium server with: **appium -p 15279 -bp 57059 --webdriveragent-port 57060 --webkit-debug-proxy-port 57061**

@chendo @zpao @ericnakagawa @bvaughn

**Comment by jswaroop** [comment]
if you are running parallel then it is recommended to use different WDA ports for both tests. They cant communicate on the same port for both tests

**Comment by rtardi** [comment]
> if you are running parallel then it is recommended to use different WDA ports for both tests. They cant communicate on the same port for both tests

Hi @jswaroop ,
I lauched the three appium server instances with different WDA port:
**appium -p 15279 -bp 57059 --webdriveragent-port 57062 --webkit-debug-proxy-port 57065
appium -p 15280 -bp 57060 --webdriveragent-port 57063 --webkit-debug-proxy-port 57066
appium -p 15281 -bp 57061 --webdriveragent-port 57064 --webkit-debug-proxy-port 57067**
...

**Comment by marekcirkos** [comment]
I wonder if this is Xcode's issue on invoking multiple tests. We use FBSimulatorControl to start WDA, rather than xcodebuild and it work well in big scale with more then 3 WDA's in parallel (sims).
