### ISSUE TITLE
wda problem

### ISSUE THREAD

**Issue by johanntony** [facebook/WebDriverAgent#1031]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/76931913-F27B-4166-BBCC-80B198C44FEF/wda/screen -- http://localhost:8100/ with parameters {
          wildcards =     (
              "session/76931913-F27B-4166-BBCC-80B198C44FEF/wda/screen"
          );
      }
      Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
      System info: host: 'jiahantangdeMacBook-Pro.local', ip: 'fe80:0:0:0:1495:a9e0:4739:2477%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '10.0.2'
      Driver info: io.appium.java_client.ios.IOSDriver
      Capabilities {autoGrantPermissions: true, automationName: Appium, browserName: , bundleId: com.bjlc.LuckinDriver, databaseEnabled: false, deviceName: iPhone(2), javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 300, noReset: true, platform: MAC, platformName: iOS, platformVersion: 12.1, resetKeyboard: true, takesScreenshot: true, udid: 68f73cf8b7676dd695ff9937a90..., unicodeKeyboard: true, webStorageEnabled: false}
      Session ID: b462a17c-dcdd-4052-8949-0a1fe13fefcd
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
      	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
      	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
      	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
      	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
      	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
      	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
      	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
      	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
      	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
      	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
      	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)
      	at com.appium.lib.seleniumcucumber.base.AppiumController.startDriver(AppiumController.java:99)
      	at com.appium.lib.seleniumcucumber.stepdefinitions.PredefinedStepDefinitions.runAppDispatch(PredefinedStepDefinitions.java:34)
      	at ✽.Given Run APP DISPATCH(IosDispach.feature:6)

why i run the python everyThing is ok,but use java IDE .

**Comment by AdityaRawat23** [comment]
I'm getting the same error with java client 7.0.0 and Appium v1.9.0,

[debug] [35m[W3C (fd533ddc)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/92468788-4223-4F52-82BD-869459ABE4A1/wda/screen -- http://localhost:8100/ with parameters {
[debug] [35m[W3C (fd533ddc)][39m     wildcards =     (
[debug] [35m[W3C (fd533ddc)][39m         "session/92468788-4223-4F52-82BD-869459ABE4A1/wda/screen"
[debug] [35m[W3C (fd533ddc)][39m     );
[debug] [35m[W3C (fd533ddc)][39m }
[debug] [35m[W3C (fd533ddc)][39m     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [35m[W3C (fd533ddc)][39m     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [35m[W3C (fd533ddc)][39m     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:234:19)
[debug] [35m[W3C (fd533ddc)][39m     at <anonymous>
[35m[HTTP][39m [37m<-- GET /wd/hub/session/fd533ddc-4e78-4340-ac78-3b6531cad170 [39m[31m500[39m [90m272 ms - 1151[39m
[35m[HTTP][39m [90m[39m

**Comment by uterator** [comment]
A similar issue reported from the Appium side - https://github.com/appium/appium/issues/10411 
Can be related. However, keeping the WDA up to date seems doesn't replicate the issue.

**Comment by fishermanjohn001** [comment]
I got the exact same problem, does anyone has some answers?

**Comment by fishermanjohn001** [comment]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'elainechendeMBP', ip: 'fe80:0:0:0:c14:7fec:aac1:4a47%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_181'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {autoAcceptAlerts: true, autoLaunch: false, automationName: XCUITest, browserName: , bundleId: com.qiyi.iphone, databaseEnabled: false, deviceName: iPhone6sPlus, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: MAC, platformVersion: 12.1.2, takesScreenshot: true, udid: 8dfce56c28e9d6d63bb01943729..., useNewWDA: false, webDriverAgentUrl: http://127.0.0.1:8100, webStorageEnabled: false}
Session ID: e51f817e-642d-4cdd-9bee-a584018a07c0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at Driver.DriverServer.baseDriver(DriverServer.java:78)
	at Monkey.run(Monkey.java:264)
	at Monkey.executeParameter(Monkey.java:218)
	at Monkey.main(Monkey.java:80)
