### ISSUE TITLE
ERROR: ESOCKETTIMEDOUT appears when trying to start tests with Jenkins on remote server

### ISSUE THREAD

**Issue by sanyco92** [facebook/WebDriverAgent#1039]
[appium.log](https://github.com/appium/appium.io/files/2648829/appium.before.adding.caps.log)

Hello Guys. I have jenkins server where I run tests with Appium 1.10.0 and WebDriver.io. I have several spec files, I run them like this:
wdio ./config/platforms/wdio.conf.ios.js --suite sync,login,settings,home,myCourses,myEvaluations,myForms,myPublications,
but for the first spec file I'm always getting error:

ERROR: ESOCKETTIMEDOUT
ipadpro(12_9-inch).ios.12_0.app365_beta_app
at new RuntimeError (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
at Request._callback (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/RequestHandler.js:332:43)
at self.callback (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:185:22)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at ClientRequest.<anonymous> (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:819:16)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at ClientRequest.emit (events.js:208:7)
at Socket.emitTimeout (_http_client.js:706:34)

Checked appium logs:
[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[35m[JSONWP Proxy][39m Got an unexpected response: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

Also, I noticed this one:
WebDriverAgent successfully started after 259484ms

Maybe someone knows how to solve the issue? Here're my capabilities:

capabilities: [{
maxInstances: 1,
platformName: 'iOS',
platformVersion: '12.0',
automationName: 'XCUITest',
orientation: 'PORTRAIT',
app: '/Users/user/Documents/projects/app365/app/ios/app365_Beta.app',
wdaLaunchTimeout: 600000,
wdaConnectionTimeout: 600000,
newCommandTimeout: 600,
clearSystemFiles: true,
noReset: false,
useJSONSource: true,
maxTypingFrequency: 10,
reduceMotion: true
}],
appium: {
waitStartTime: 90000,
logFileName: 'appium.log',
args: {
address: 'localhost',
port: 4723,
commandTimeout: '7200',
sessionOverride: true,
debugLogSpacing: true
}
},

Then I added the following capabilities, but it didn't help (see the log file [appium (after adding caps).log](https://github.com/appium/appium.io/files/2648830/appium.after.adding.caps.log):
wdaStartupRetries: 5,
wdaStartupRetryInterval: 60000,
useNewWDA: true.

I have a weak computer configuration on remote, so maybe I need to increase some timeouts or something. Please, help.

**Comment by sanyco92** [comment]
Here're my Appium Logs including Xcode logs:
[appium_xcodeLogs.log](https://github.com/facebook/WebDriverAgent/files/2653944/appium_xcodeLogs.log)

**Comment by rafaelcs** [comment]
Try to set another port in your capabilities, like `wdaLocalPort: 8110`

**Comment by sanyco92** [comment]
> Try to set another port in your capabilities, like `wdaLocalPort: 8110`

Tried, it didn't help. The error occurs after 16 min of waiting, every time.

15:18:23 [1;30m[07:18:23] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
15:18:23 [1;30m[07:18:23] [0m [0;33mDATA		[0m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":1,"platformName":"iOS","platformVersion":"12.0","automationName":"XCUITest","orientation":"PORTRAIT","app":"/Users/company/.jenkins/workspace/app-automation-ios/app/ios/app365_Beta.app","_":"11 more keys: [\"showXcodeLog\",\"wdaLaunchTimeout\",\"wdaConnectionTimeout\",\"newCommandTimeout\",\"clearSystemFiles\",\"noReset\",\"maxTypingFrequency\",\"wdaLocalPort\",\"deviceName\",\"deviceType\",\"requestOrigins\"]"}}
15:34:23 ERROR: ESOCKETTIMEDOUT
15:34:23 ipadpro(12_9-inch).ios.12_0.app365_beta_app
15:34:23     at new RuntimeError (/Users/user/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
15:34:23     at Request._callback (/Users/user/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/RequestHandler.js:332:43)
15:34:23     at self.callback (/Users/user/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:185:22)
15:34:23     at Request.emit (events.js:189:13)
15:34:23     at Request.EventEmitter.emit (domain.js:441:20)
15:34:23     at ClientRequest.<anonymous> (/Users/user/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:819:16)
15:34:23     at Object.onceWrapper (events.js:277:13)
15:34:23     at ClientRequest.emit (events.js:189:13)
15:34:23     at ClientRequest.EventEmitter.emit (domain.js:441:20)
15:34:23     at Socket.emitRequestTimeout (_http_client.js:668:40)

**Comment by rafaelcs** [comment]
Is this the complete log? @sanyco92

**Comment by sanyco92** [comment]
> Is this the complete log? @sanyco92

Complete log attached in the topic. This is a part of Jenkins console logs, but after this error other suites work correctly and a new session started successfully. I don't see any errors except this.

**Comment by sanyco92** [comment]
> Is this the complete log? @sanyco92

[jenkins_logs.txt](https://github.com/facebook/WebDriverAgent/files/2690824/jenkins_logs.txt)
Please, check these logs from Jenkins.
