### ISSUE TITLE
Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window -25201" UserInfo={NSLocalizedDescription=Error getting main window -25201}

### ISSUE THREAD

**Issue by vky26** [facebook/WebDriverAgent#1074]
Hey Guys, the app crashes only when I run with below configuration. 
Any help on this please? 

Im using, Appium, Serenity, JBehave with JAVA for mobile automation

JAVA Version - 1.8.0_161
Appium Version - 1.10.0
<serenity.version>1.9.17</serenity.version>
<serenity.jbehave.version>1.42.0</serenity.jbehave.version>
XCode Version: 10.1
Mac OS: 10.13.6

**Note:**
**iPhone X - 11.0.1  - Problem Exist, app crashes and throws the below**

> iPhone 8 - 12.0.1 - Script runs fine, no issues 

Signed freshly for both the phones

<img width="925" alt="error" src="https://user-images.githubusercontent.com/38526589/52293989-09dc0180-2970-11e9-8977-f865ad4098f1.png">

![wda project](https://user-images.githubusercontent.com/30401839/52295053-bf0fb900-2972-11e9-88de-22abf40c5a86.png)

Server Logs:
[MJSONWP (820badfb)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name='heating.control.infobar']","820badfb-2104-49e1-a713-8628df3cfe6d"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator 
strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 2000 ms for condition
[JSONWP Proxy] Matched '/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/DD89C88E-1192-4105-B299-899CD6104C63/element] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name='heating.control.infobar']"}
[Xcode] 2019-02-05 18:01:36.327114+0000 WebDriverAgentRunner-Runner[648:180060] Getting the snapshot timed out after 15 seconds
[Xcode] 2019-02-05 18:01:36.327431+0000 WebDriverAgentRunner-Runner[648:180060] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window -25201" UserInfo={NSLocalizedDescription=Error getting main window -25201}
[Xcode] t = 193.61s Snapshot accessibility hierarchy for app with pid 651
[Xcode] 
[Xcode] 2019-02-05 18:01:36.338808+0000 WebDriverAgentRunner-Runner[648:180060] Skipping source dumping for Window because its snapshot cannot be resolved
[Xcode] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[JSONWP Proxy] Got response with status 200: {"value":{"using":"xpath","value":"//XCUIElementTypeOther[@name='heating.control.infobar']","description":"unable to find an element"},"sessionId":"DD89C88E-1192-4105-B299-899CD6104C63","status":7}
[JSONWP Proxy] Got an unexpected response: {"value":{"using":"xpath","value":"//XCUIElementTypeOther[@name='heating.control.infobar']","description":"unable to find an element"},"sessionId":"DD89C88E-1192-4105-B299-899CD6104C63","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[MJSONWP (820badfb)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[MJSONWP (820badfb)] at XCUITestDriver.helpers.doNativeFind (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[MJSONWP (820badfb)] at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/element 500 3176 ms - 164
[HTTP] 
[HTTP] --> GET /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/screenshot
[HTTP] {}
[MJSONWP (820badfb)] Calling AppiumDriver.getScreenshot() with args: ["820badfb-2104-49e1-a713-8628df3cfe6d"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/DD89C88E-1192-4105-B299-899CD6104C63/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAABVmlDQ1BJQ0MgUHJv\\r\\nZmlsZQAAKJFjYGBSSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8jADoS8DGIMConJxQWO\\r\\nAQE+QCUMMBoVfLvGwAiiL+uCzDolNbVJtV7A12Km8NWLr0SbMNWjAK6U1OJkIP0H\\r\\niFOTC4pKGBgYU4Bs5fKSAhC7A8gWKQI6CsieA2KnQ9gbQOwkCPsIWE1IkDOQfQPI\\r\\nVkjOSASawfgDyNZJQhJPR2JD7QUBbpfM4oKcxEqFAGMCriUDlKRWlIBo5\\/yCyqLM\\r\\n9IwSBUdgKKUqeOYl6+koGBkYmjMwgMIcovpzIDgsGcXOIMSa7zMw2O7\\/\\/\\/\\/\\/boSY\\r\\n134Gho1AnVw7EWIaFgwMgtwMDCd2FiQWJYKFmIGYKS2NgeHTcgYG3kgGBuELQD3R\\r\\nxWnGRmB5Rh4nBgbWe\\/\\/\\/f1ZjYGCfzMDwd8L\\/\\/78X\\/f\\/\\/dzFQ8x0GhgN5ABUhZe60\\r\\nf\\/npAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAHawvKVDSTgAAQABJ\\r\\nREFUeAGEnQmvZTeuXo082zXcmstuj3XneajBNXnqRvKSvAQJECD\\/\\/89kkUv6ju65\\r\\n7g7AI3Bra0sUSVGkpL3PF0+Prp8cXj3av9jZOxce7p49eHWayy2EWwLFHh9cAj57\\r\\n\\/+eTAI+QKVDMCrl776djUi65RSVbOVQFJdzN4\\/PBo\\/s\\/D3jw6jgwM0+oipKz8IYM\\r\\n8reI55JitG5bdvzhLo8ckT7ap0cwgdogsi6fHNILym+AuylgMVOoCj30KyyyORp6\\r\\n8OocuP8zdNI6PL8h3dm7DD0g8OfrH494FvIklUxqk1HcBb764...
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[MJSONWP (820badfb)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAABVmlDQ1BJQ0MgUHJv\r\nZmlsZQAAKJFjYGBSSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8jADoS8DGIMConJxQWO\r\nAQE+QCUMMBoVfLvGwAiiL+uCzDolNbVJtV7A12Km8NWLr0SbMNWjAK6U1OJkIP0H\r\niFOTC4pKGBgYU4Bs5fKSAhC7A8gWKQI6CsieA2KnQ9gbQOwkCPsIWE1IkDOQfQPI\r\nVkjOSASawfgDyNZJQhJPR2JD7QUBbpfM4oKcxEqFAGMCriUDlKRWlIBo5/yCyqLM\r\n9IwSBUdgKKUqeOYl6+koGBkYmjMwgMIcovpzIDgsGcXOIMSa7zMw2O7/////boSY\r\n134Gho1AnVw7EWIaFgwMgtwMDCd2FiQWJYKFmIGYKS2NgeHTcgYG3kgGBuELQD3R\r\nxWnGRmB5Rh4nBgbWe///f1ZjYGCfzMDwd8L//78X/f//dzFQ8x0GhgN5ABUhZe60\r\nf/npAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAHawvKVDSTgAAQABJ\r\nREFUeAGEnQmvZTeuXo082zXcmstuj3XneajBNXnqRvKSvAQJECD//89kkUv6ju65\r\n7g7AI3Bra0sUSVGkpL3PF0+Prp8cXj3av9jZOxce7p49eHWayy2EWwLFHh9cAj57\r\n/+eTAI+QKVDMCrl776djUi65RSVbOVQFJdzN4/PBo/s/D3jw6jgwM0+oipKz8IYM\r\n8reI55JitG5bdvzhLo8ckT7ap0cwgdogsi6fHNILym+AuylgMVOoCj30KyyyORp6\r\n8OocuP8zdNI6PL8h3dm7DD0g8OfrH494FvIklUxqk1HcBb764ZDUrlFtQG7LuvQO\r\n5PH+64KD60f78PYCSBkQqYIM7j7au9nZvSaHy8B8pAo0tTyOmG6E6sLB9cP9qwd0\r\n...
[HTTP] <-- GET /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/screenshot 200 641 ms - 5722194
[HTTP] 
[HTTP] --> GET /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/screenshot
[HTTP] {}
[MJSONWP (820badfb)] Calling AppiumDriver.getScreenshot() with args: ["820badfb-2104-49e1-a713-8628df3cfe6d"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/DD89C88E-1192-4105-B299-899CD6104C63/screenshot] with no body
[iProxy] l: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] waiting for connection
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] waiting for connection
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] waiting for connection
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] waiting for connection
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] waiting for connection
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] waiting for connection
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] run_ctos_loop: fd = 7
[iProxy] run_stoc_loop: fd = 7
[iProxy] accepted connection, fd = 7
[iProxy] Number of available devices == 1
[iProxy] Requesting connecion to device handle == 5 (serial: 85aa1648cf9a7fbd9950a5338e24ddb6e678065c), port 8100
[iProxy] wait
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAABVmlDQ1BJQ0MgUHJv\\r\\nZmlsZQAAKJFjYGBSSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8jADoS8DGIMConJxQWO\\r\\nAQE+QCUMMBoVfLvGwAiiL+uCzDolNbVJtV7A12Km8NWLr0SbMNWjAK6U1OJkIP0H\\r\\niFOTC4pKGBgYU4Bs5fKSAhC7A8gWKQI6CsieA2KnQ9gbQOwkCPsIWE1IkDOQfQPI\\r\\nVkjOSASawfgDyNZJQhJPR2JD7QUBbpfM4oKcxEqFAGMCriUDlKRWlIBo5\\/yCyqLM\\r\\n9IwSBUdgKKUqeOYl6+koGBkYmjMwgMIcovpzIDgsGcXOIMSa7zMw2O7\\/\\/\\/\\/\\/boSY\\r\\n134Gho1AnVw7EWIaFgwMgtwMDCd2FiQWJYKFmIGYKS2NgeHTcgYG3kgGBuELQD3R\\r\\nxWnGRmB5Rh4nBgbWe\\/\\/\\/f1ZjYGCfzMDwd8L\\/\\/78X\\/f\\/\\/dzFQ8x0GhgN5ABUhZe60\\r\\nf\\/npAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAHaqdWmWnaAAAQABJ\\r\\nREFUeAGEnQmvZTeuXo082zXcmstuj3XneajBNXnqRvKSvAQJECD\\/\\/89kkUv6ju65\\r\\n7g7AI3Bra0sUSVGkpL3PF0+Prp8cXj3av9jZOxce7p49eHWayy2EWwLFHh9cAj57\\r\\n\\/+eTAI+QKVDMCrl776djUi65RSVbOVQFJdzN4\\/PBo\\/s\\/D3jw6jgwM0+oipKz8IYM\\r\\n8reI55JitG5bdvzhLo8ckT7ap0cwgdogsi6fHNILym+AuylgMVOoCj30KyyyORp6\\r\\n8OocuP8zdNI6PL8h3dm7DD0g8OfrH494FvIklUxqk1HcBb764...
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[MJSONWP (820badfb)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAABVmlDQ1BJQ0MgUHJv\r\nZmlsZQAAKJFjYGBSSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8jADoS8DGIMConJxQWO\r\nAQE+QCUMMBoVfLvGwAiiL+uCzDolNbVJtV7A12Km8NWLr0SbMNWjAK6U1OJkIP0H\r\niFOTC4pKGBgYU4Bs5fKSAhC7A8gWKQI6CsieA2KnQ9gbQOwkCPsIWE1IkDOQfQPI\r\nVkjOSASawfgDyNZJQhJPR2JD7QUBbpfM4oKcxEqFAGMCriUDlKRWlIBo5/yCyqLM\r\n9IwSBUdgKKUqeOYl6+koGBkYmjMwgMIcovpzIDgsGcXOIMSa7zMw2O7/////boSY\r\n134Gho1AnVw7EWIaFgwMgtwMDCd2FiQWJYKFmIGYKS2NgeHTcgYG3kgGBuELQD3R\r\nxWnGRmB5Rh4nBgbWe///f1ZjYGCfzMDwd8L//78X/f//dzFQ8x0GhgN5ABUhZe60\r\nf/npAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAHaqdWmWnaAAAQABJ\r\nREFUeAGEnQmvZTeuXo082zXcmstuj3XneajBNXnqRvKSvAQJECD//89kkUv6ju65\r\n7g7AI3Bra0sUSVGkpL3PF0+Prp8cXj3av9jZOxce7p49eHWayy2EWwLFHh9cAj57\r\n/+eTAI+QKVDMCrl776djUi65RSVbOVQFJdzN4/PBo/s/D3jw6jgwM0+oipKz8IYM\r\n8reI55JitG5bdvzhLo8ckT7ap0cwgdogsi6fHNILym+AuylgMVOoCj30KyyyORp6\r\n8OocuP8zdNI6PL8h3dm7DD0g8OfrH494FvIklUxqk1HcBb764ZDUrlFtQG7LuvQO\r\n5PH+64KD60f78PYCSBkQqYIM7j7au9nZvSaHy8B8pAo0tTyOmG6E6sLB9cP9qwd0\r\n...
[HTTP] <-- GET /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/screenshot 200 609 ms - 5721626
[HTTP] 
[HTTP] --> POST /wd/hub/session/820badfb-2104-49e1-a713-8628df3cfe6d/timeouts
[HTTP] {"type":"implicit","ms":0}

**Comment by vky26** [comment]
@mykola-mokhnach or someone any pointers on this please?

**Comment by vky26** [comment]
The below is similar log for other scenario, if it helps

[HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[contains(@name,\"schedule.fab.button\")]"}
[Xcode] 2019-02-06 14:33:49.671156+0000 WebDriverAgentRunner-Runner[375:84132] Getting the snapshot timed out after 15 seconds
[Xcode] 2019-02-06 14:33:49.671371+0000 WebDriverAgentRunner-Runner[375:84132] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot." UserInfo={accessibility-error=-25204, NSLocalizedDescription=Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.}
[Xcode]     t =   135.93s Snapshot accessibility hierarchy for app with pid 378
[Xcode] 
[Xcode]     t =   135.93s Snapshot accessibility hierarchy for app with pid 378
[Xcode] 
[Xcode]     t =   154.39s Get all elements bound by accessibility element for: Elements matching predicate 'wdUID IN {"05000000-0000-0000-7A01-000000000000", "8C000000-0000-0000-7A01-000000000000", "06000000-0000-0000-7A01-000000000000"} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode] 
[Xcode]     t =   154.40s     Snapshot accessibility hierarchy for app with pid 378
[Xcode]

**Comment by chandanijain9** [comment]
I am facing the same issue, when there are more than 200 cells to fetch. The  app becomes non-responsive and crashes after some time.

Any help is appreciated.

Appium version : -  1.12.1
Mac OS :- 10.13.6
Java version :- 1.8.0_144


Thanks !!

**Comment by caifancito** [comment]
Same issue here. When there are a lot of cells to fetch (see comment above) the app crashes.

Appium Desktop version : 1.13.0
MacOS: 10.14.5
Xcode: 10.2.1
appium-dot-net: 4.0.0.5-beta
Simulator and real device
iOS: 11.4, 12.1,

**Comment by Thejdeepreddyputtaparthi** [comment]
Any solution for this issue, even I am facing the same one? @caifancito @vky26 @chandanijain9

**Comment by willisfeng** [comment]
I also have this problem. Is there a solution? Input list was originally loaded with one page of data, but the continuous downward loading of data, resulting in too much data, causing this problem.

**Comment by willisfeng** [comment]
@esnyder262

**Comment by chandanijain9** [comment]
> Any solution for this issue, even I am facing the same one? @caifancito @vky26 @chandanijain9 @mykola-mokhnach

The issue did not occur after update to below versions:
MAC OS- 10.14
Appium  - 1.13
Devices with latest OS .

**Comment by willisfeng** [comment]
Still have this problem.
------------------------------------------------
MAC OS- 10.14.5
Appium - 1.13
Devices   OS -12.0
----------------------------------------------------------------------------------------------------------
[Xcode] 2019-07-23 15:31:01.298251+0800 WebDriverAgentRunner-Runner[2902:16513] Enqueue Failure: Error getting main window kAXErrorIPCTimeout /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-07-23 15:31:01.300112+0800 WebDriverAgentRunner-Runner[2902:16513] Getting the snapshot timed out after 15 seconds
[Xcode] 
[Xcode] 2019-07-23 15:31:01.300302+0800 WebDriverAgentRunner-Runner[2902:16513] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorIllegalArgument" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorIllegalArgument}
