### ISSUE TITLE
Matched JSONWP error code 13 to UnknownError

### ISSUE THREAD

**Issue by aureliendelrue** [facebook/WebDriverAgent#1080]
## The problem

For some test cases, we have the following error `Matched JSONWP error code 13 to UnknownError` when interacting with an element. We don't understand why it's not working and we need help please. Test cases are working fine on Android devices.

**Example :**
`[debug] [35m[WD Proxy][39m Proxying [POST /actions] to [POST http://localhost:8026/session/01DAE430-6B1C-44AB-B8E6-C2D0FC5D5D3E/actions] with body: {"actions":[{"id":"default mouse","type":"pointer","parameters":{"pointerType":"touch"},"actions":[{"duration":100,"x":0,"y":0,"type":"pointerMove","origin":{"element-6066-11e4-a52e-4f735466cecf":"5000","ELEMENT":"5000"}},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}]}]}
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Unsupported origin type '{\n    ELEMENT = 5000;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5000;\n}' is set for '{\n    duration = 100;\n    origin =     {\n        ELEMENT = 5000;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5000;\n    };\n    type = pointerMove;\n    x = 0;\n    y = 0;\n}' action item. Supported origin types: (\n    pointer,\n    viewport\n) or an element instance\" UserInfo={NSLocalizedDescription=Unsupported origin type '{\n    ELEMENT = 5000;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5000;\n}' is set for '{\n    duration = 100;\n    origin =     {\n        ELEMENT = 5000;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5000;\n    };\n    type = pointerMove;\n    x = 0;\n    y = 0;\n}' action item. Supported origin types: (\n    pointer,\n    viewport\n) or an element instance}","sessionId":"01DAE430-6B1C-44AB-B8E6-C2D0FC5D5D3E","status":13}
[35m[WD Proxy][39m Got an unexpected response: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Unsupported origin type '{\n    ELEMENT = 5000;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5000;\n}' is set for '{\n    duration = 100;\n    origin =     {\n        ELEMENT = 5000;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5...
[debug] [35m[MJSONWP][39m Matched JSONWP error code 13 to UnknownError
[debug] [35m[XCUITest][39m Connection to WDA timed out
[debug] [35m[iProxy][39m recv failed: Operation not permitted
[debug] [35m[W3C (2088b021)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Unsupported origin type '{
[debug] [35m[W3C (2088b021)][39m     ELEMENT = 5000;
[debug] [35m[W3C (2088b021)][39m     "element-6066-11e4-a52e-4f735466cecf" = 5000;
[debug] [35m[W3C (2088b021)][39m }' is set for '{
[debug] [35m[W3C (2088b021)][39m     duration = 100;
[debug] [35m[W3C (2088b021)][39m     origin =     {
[debug] [35m[W3C (2088b021)][39m         ELEMENT = 5000;
[debug] [35m[W3C (2088b021)][39m         "element-6066-11e4-a52e-4f735466cecf" = 5000;
[debug] [35m[W3C (2088b021)][39m     };
[debug] [35m[W3C (2088b021)][39m     type = pointerMove;
[debug] [35m[W3C (2088b021)][39m     x = 0;
[debug] [35m[W3C (2088b021)][39m     y = 0;
[debug] [35m[W3C (2088b021)][39m }' action item. Supported origin types: (
[debug] [35m[W3C (2088b021)][39m     pointer,
[debug] [35m[W3C (2088b021)][39m     viewport
[debug] [35m[W3C (2088b021)][39m ) or an element instance" UserInfo={NSLocalizedDescription=Unsupported origin type '{
[debug] [35m[W3C (2088b021)][39m     ELEMENT = 5000;
[debug] [35m[W3C (2088b021)][39m     "element-6066-11e4-a52e-4f735466cecf" = 5000;
[debug] [35m[W3C (2088b021)][39m }' is set for '{
[debug] [35m[W3C (2088b021)][39m     duration = 100;
[debug] [35m[W3C (2088b021)][39m     origin =     {
[debug] [35m[W3C (2088b021)][39m         ELEMENT = 5000;
[debug] [35m[W3C (2088b021)][39m         "element-6066-11e4-a52e-4f735466cecf" = 5000;
[debug] [35m[W3C (2088b021)][39m     };
[debug] [35m[W3C (2088b021)][39m     type = pointerMove;
[debug] [35m[W3C (2088b021)][39m     x = 0;
[debug] [35m[W3C (2088b021)][39m     y = 0;
[debug] [35m[W3C (2088b021)][39m }' action item. Supported origin types: (
[debug] [35m[W3C (2088b021)][39m     pointer,
[debug] [35m[W3C (2088b021)][39m     viewport
[debug] [35m[W3C (2088b021)][39m ) or an element instance}
[debug] [35m[W3C (2088b021)][39m     at errorFromMJSONWPStatusCode (/Users/teamqualite/Documents/mobile-platform/iOS/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [35m[W3C (2088b021)][39m     at ProxyRequestError.getActualError (/Users/teamqualite/Documents/mobile-platform/iOS/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [35m[W3C (2088b021)][39m     at JWProxy.command (/Users/teamqualite/Documents/mobile-platform/iOS/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:234:19)
[debug] [35m[W3C (2088b021)][39m     at <anonymous>`

## Environment
* Appium version (or git revision) that exhibits the issue: 1.11.1
* Desktop OS/version used to run Appium: Mac OS 10.14.1
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: iOS12.1
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe: Appium CLI installed with npm
* Others : Appium node connected to Selenium Hub (3.14)

## Details

Log Appium : [GIST](https://gist.github.com/aureliendelrue/f0370af489f194c7fab05bddfce2a3c9)

**Comment by mykola-mokhnach** [comment]
It does not work, because W3C Actions are only supported in native context and you're trying to perform them on elements from the web context.

**Comment by aureliendelrue** [comment]
Hi @mykola-mokhnach, you mean Appium sends wrong command to WDA for a web context ?

**Comment by mykola-mokhnach** [comment]
No I mean Actions API is not supported by mobile Safari at all

**Comment by aureliendelrue** [comment]
I understand, so how can we test on safari mobile ? Maybe I forgot a capability in Appium to specify i'm testing on safari mobile...

**Comment by Ganpal** [comment]
I am seeing this issue on appium v.1.11 for Mac v10.13.6 on iOS Simulator v12.1

**Comment by aureliendelrue** [comment]
@Ganpal this issue and Appium issue are in standby... we should compare our capabilities, maybe we are missing something...

**Comment by paulinedess** [comment]
Hi, I got similar issue. Is there a way to test on safari @mykola-mokhnach ?
