### ISSUE TITLE
Showing All Messages :-1: An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle'. (in target 'WebDriverAgentRunner')

### ISSUE THREAD

**Issue by LiebeKrake** [facebook/WebDriverAgent#1107]
I had installed appium-xcuitest-driver,  performed the following steps
`
```shell
   cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
   mkdir -p Resources/WebDriverAgent.bundle
   ./Scripts/bootstrap.sh
````
But I got errors as bellow：
`TestCenter-WuHandeMac-mini:WebDriverAgent testcenter_wuhan$ ./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN web-driver-inspector@1.0.0 No repository field.

audited 2594 packages in 5.156s
found 16 vulnerabilities (6 low, 4 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Validating Inspector
Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
Error: Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:260:26)
`

someone said it didnot matter（If not, please point out）,
[https://github.com/facebook/WebDriverAgent/issues/558](url)

> 

This is definitely Appium issue. We do not use eslint-config-appium
--

So I turned to compile directly：
When I try to compile（provisioning profile has been set, bundle idetifier has been changed）, I get “Build Failure”. The error details are “Showing All Messages :-1: An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle'. (in target 'WebDriverAgentRunner')”

Environment：
macOS：10.14.4
appium：1.9.1
nodeJS：10.15.2
npm：6.4.1

Pls help me.

**Comment by yananester** [comment]
I face the same issue:

`WebDriverAgent yn-sleepscore$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=942a1abd5ba42da79f9f0277d303f7b04403dd66' test
note: Using new build system
note: Planning build
note: Using build description from disk
Build system information
error: An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle'. (in target 'WebDriverAgentRunner')

2019-05-11 20:25:24.621 xcodebuild[4865:1435287]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14490.122/IDEFoundation/Logging/ActivityLog/IDEActivityLogSectionRecorder.m:1050
Details:  log recorder was sent -stopRecordingWithInfo:completionBlock: after it had already been asked to stop recording.
Object:   <IDEActivityLogSectionRecorder: 0x7fd9980c8120>
Method:   -stopRecordingWithInfo:completionBlock:
Thread:   <NSThread: 0x7fd995410f10>{number = 10, name = (null)}
Please file a bug at https://bugreport.apple.com with this warning message and any useful information you can provide.

Testing failed:
	An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle'. (in target 'WebDriverAgentRunner')
	Testing cancelled because the build failed.

Test session results and logs:
	/Users/yn-sleepscore/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.05.11_20-25-24--0700.xcresult

** TEST FAILED **`

**Comment by mgrybyk** [comment]
Hey,

I had the same issue, solved it like this.

1. Choose **WebDriverAgentRunner** in Targets
![image](https://user-images.githubusercontent.com/25589559/57930384-1c8e9c80-78b6-11e9-943c-3c8b9e32f893.png)

2. Open Build Settings
3. Type identity in search box
4. Choose iOS Developer
![image](https://user-images.githubusercontent.com/25589559/57930428-3fb94c00-78b6-11e9-98a5-ff9d4a0795b0.png)

That's. Hope that helps!

@LiebeKrake @yananester

**Comment by anhmainvg** [comment]
@yananester I have faced the same issue and resolved it by following Appium tutorial [Full manual configuration](http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/), but you might find it's too long and too technical to read, and hint from @mgrybyk , but his device looks different 
Generally, do the following procedures:
1. Find your project path node_module/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
if you installed appium globally, so it should be in the path

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

2. Open terminal 
Run the following commands (in order to create Resources folder with Bundleid) and install the dependencies

cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d
3. Wait untils dependencie installed , my understanding is, the following frameworks are installed
![image](https://user-images.githubusercontent.com/43400649/57964474-54eab500-7960-11e9-8713-d6400d6131d1.png)

you can observe in the folder of step 1, the folder "Resouce" is now created

4. Open the file WebDriverAgent.xcodeproj
5. Find the **WebDriverAgentRunner**  and **Integration App** under Target (see images of @mgrybyk above)
6. Select "Automatically Manage Signing
Actual Result: You should see the Error 
![image](https://user-images.githubusercontent.com/43400649/57964553-28836880-7961-11e9-89d5-fe0ce3ffb9fa.png)


Now go to Build Settings tab and find the "Product Bundle Identifier", replace the default one with any string
Back to General Tab
=> now you should be able to build without Error

**Comment by degamer106** [comment]
Got this same issue running Appium 1.13 on iOS 12.3.  None of the solutions posted above worked.  Can anyone from the Appium team look into this?

**Comment by KazuCocoa** [comment]
what about using the latest `appium@beta` and the latest carthage?
We've tweeted some cases for signing for upcoming 1.13.1 (current `@beta`)

**Comment by zcmgyu** [comment]
I confirm that this issue has resolved in 1.14@beta1 version, when WebDriverAgentRunner's code signing changed from 'manual' to 'automation'

https://github.com/appium/appium-xcuitest-driver/pull/961
