### ISSUE TITLE
Can we have multiple instances of WebdriverAgentRunner (running on different ports)?

### ISSUE THREAD

**Issue by upasnapandey** [facebook/WebDriverAgent#216]
xcodebuild test -project <path>/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' PORT=8500

I want to run multiple instances of WebDriverAgent on different ports. This command works fine when only single instance is run. As soon as we trigger a similar command with a different PORT number, previous runner fails.
can you please help with this? is there any setting for parallel test execution?

Thanks.

**Comment by marekcirkos** [comment]
Launching multiple WDA instances within one simulator definitely wouldn't work and it wouldn't make much sense either. This is because tested application must be active in order to interact with it.

However you can launch multiple simulators with one WDA instance per simulator on different ports. You can't do this with `xcodebuild` however you definitely can do this with [fbsimctl](https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl). You should check it out ;)

**Comment by thejuskrishna** [comment]
I think the author meant Multiple instances of WDA on multiple devices to support parallel runs. 
@upasnapandey pls confirm 

At present even if you launch two instances (device#1 and device#2 respectively) of Appium say one on port 4723 and other on port 4727, WDA is launched only on localhost:8100. The run in 4727 (if triggered after 4723) will fail because the run happening in 4723 has already launched WDA on 8100 on device#1. 

```
ERROR: test_ui_computation (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple_4727.py", line 72, in setUp
    'udid': '5a991add125e8aa7810c2fae70d9288530c4dde7'
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: iproxy exited with code '208'
```

**Comment by thejuskrishna** [comment]
Adding the error from appium as well:
```
[debug] [iProxy] Error creating socket: Address already in use
[XCUITest] iproxy exited with code '208'
[XCUITest] Error: iproxy exited with code '208'
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:438:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:192:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: iproxy exited with code '208'
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:438:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:192:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
```

**Comment by marekcirkos** [comment]
@thejuskrishna You should raise this issue with Appium as this is matter of Appium supporting it. As I mentioned You can launch multiple simulators/devices with one WDA instances per simulator/device. All you need to do is set different port for each one.

**Comment by MukundMuralidharan** [comment]
how to set different port for each simulator? please point me to that page. I will really appreciate it.

**Comment by arafatmeister** [comment]
HI pal. @MukundMuralidharan  you should launch different Appium instances specifying different WDA ports using this parameter, for example appium -p 4729 --webdriveragent-port 8200
