### ISSUE TITLE
xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by oatsuper** [facebook/WebDriverAgent#257]
Maybe my wda' running status is well,
/usr/bin/codesign --force --sign A48B4FADAFC2F43AAF96CEB6D878D20772DC9B33 --deep --entitlements /Users/yanyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cpjxhytkhbaxuceopaxbddbfdnnv/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/yanyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cpjxhytkhbaxuceopaxbddbfdnnv/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/Users/yanyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cpjxhytkhbaxuceopaxbddbfdnnv/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/0p/0h6lwsp92_j8g_jrbplv0mww0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/160a3918132918310cbc5cf41f306173/71d50cc5e99828132b58a4daf43c2b02edeb9f6a/ManifestCache.plist
2016-08-23 14:56:07.158 XCTRunner[574:106516] Running tests...
14:56:07.393 XCTRunner[574:106534] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
14:56:07.510 XCTRunner[574:106538] _IDE_startExecutingTestPlanWithProtocolVersion:16
2016-08-23 14:56:07.837 XCTRunner[574:106516] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2016-08-23 14:56:08.514
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-08-23 14:56:08.517
Test Suite 'UITestingUITests' started at 2016-08-23 14:56:08.518
Test Case '-[UITestingUITests testRunner]' started.

but i take my client to connect localhost:8100, but got below error:
equests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /session (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10c889450>: Failed to establish a new connection: [Errno 61] Connection refused',))

How can I to do check my env ?

**Comment by oatsuper** [comment]
modify error info:
xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8100
/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^
Error: >> proxy.js:58:18 [master] pid:56878 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8100
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

**Comment by marekcirkos** [comment]
I can see that you are starting WDA on device, which means that you should be using actually device IP instead of `localhost`.

**Comment by oatsuper** [comment]
Thanks~
