### ISSUE TITLE
cannot use either bundled inspector nor appium inspector

### ISSUE THREAD

**Issue by toejough** [facebook/WebDriverAgent#317]
When using the appium osx app, version 1.5.3, if I try to connect to localhost:8100 as my server, I get an error that Appium can't list the sessions:
<img width="532" alt="screen shot 2016-10-05 at 10 00 31 pm" src="https://cloud.githubusercontent.com/assets/5317312/19138125/5d2e65cc-8b47-11e6-8bab-b9f594fa5355.png">

If I connect with the standard appium port (4723), I get roughly the same dialog, except the error is that it cannot create a new session (which is fine, because all I want is to inspect the one current session).

When trying to use this project's inspector directly, via `http://localhost:8100/inspector`, I get a response back which I'm having a hard time parsing something actionable out of:

```
{
value: "Invalid parameter not satisfying: path

(
	0   CoreFoundation                      0x000000010c8a134b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c30221e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c8a5442 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010be98edd -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   WebDriverAgentLib                   0x000000011b0dec8b -[FBResponseFilePayload initWithFilePath:] + 283
	5   WebDriverAgentLib                   0x000000011b0dac17 FBResponseFileWithPath + 87
	6   WebDriverAgentLib                   0x000000011b0ebdbc __29+[FBInspectorCommands routes]_block_invoke + 108
	7   WebDriverAgentLib                   0x000000011b0daedc -[FBRoute_Sync mountRequest:intoResponse:] + 140
	8   WebDriverAgentLib                   0x000000011b0d3374 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
	9   RoutingHTTPServer                   0x000000011b1a3c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	10  RoutingHTTPServer                   0x000000011b1a44fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	11  libdispatch.dylib                   0x000000010f5c412e _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010f5ac7a5 _dispatch_barrier_sync_f_slow_invoke + 315
	13  libdispatch.dylib                   0x000000010f5c412e _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010f5ab52d _dispatch_main_queue_callback_4CF + 1054
	15  CoreFoundation                      0x000000010c8654f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x000000010c82af8d __CFRunLoopRun + 2205
	17  CoreFoundation                      0x000000010c82a494 CFRunLoopRunSpecific + 420
	18  Foundation                          0x000000010bde5080 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	19  Foundation                          0x000000010bde4f5b -[NSRunLoop(NSRunLoop) run] + 76
	20  WebDriverAgentLib                   0x000000011b0d22b6 -[FBWebServer startServing] + 262
	21  WebDriverAgentRunner                0x000000011ac5dab4 -[UITestingUITests testRunner] + 100
	22  CoreFoundation                      0x000000010c82805c __invoking___ + 140
	23  CoreFoundation                      0x000000010c827ee1 -[NSInvocation invoke] + 289
	24  XCTest                              0x000000010bcda210 __24-[XCTestCase invokeTest]_block_invoke_2 + 481
	25  XCTest                              0x000000010bd129d4 -[XCTestContext performInScope:] + 190
	26  XCTest                              0x000000010bcda01c -[XCTestCase invokeTest] + 255
	27  XCTest                              0x000000010bcda835 -[XCTestCase performTest:] + 457
	28  XCTest                              0x000000010bcd78fd -[XCTestSuite performTest:] + 491
	29  XCTest                              0x000000010bcd78fd -[XCTestSuite performTest:] + 491
	30  XCTest                              0x000000010bcd78fd -[XCTestSuite performTest:] + 491
	31  XCTest                              0x000000010bcc3b0c __25-[XCTestDriver _runSuite]_block_invoke + 51
	32  XCTest                              0x000000010bce4fc3 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602
	33  XCTest                              0x000000010bcc39a9 -[XCTestDriver _runSuite] + 436
	34  XCTest                              0x000000010bcc47a2 -[XCTestDriver _checkForTestManager] + 287
	35  XCTest                              0x000000010bd13f5c _XCTestMain + 628
	36  CoreFoundation                      0x000000010c84625c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	37  CoreFoundation                      0x000000010c82b304 __CFRunLoopDoBlocks + 356
	38  CoreFoundation                      0x000000010c82aa75 __CFRunLoopRun + 901
	39  CoreFoundation                      0x000000010c82a494 CFRunLoopRunSpecific + 420
	40  GraphicsServices                    0x000000010ed02a6f GSEventRunModal + 161
	41  UIKit                               0x000000010ccc4f34 UIApplicationMain + 159
	42  XCTRunner                           0x000000010bc4481c XCTRunner + 6172
	43  libdyld.dylib                       0x000000010f60d68d start + 1
)",
sessionId: "14A34247-3ABF-4EE2-B081-4205516555FC",
status: 13
}
```

I'm using https://github.com/facebook/WebDriverAgent/tree/2158a8d0f305549532f1338fe1e4628cfbd53cd9 in appium 1.6.0-beta3.

Am I doing something wrong?  Is there something I can change locally, or can contribute a PR to fix?  

I'm using xcode `Version 8.0 (8A218a)`, and the latest chrome, on osx 10.11.6, if that helps anything.

**Comment by marekcirkos** [comment]
I think you didn't build inspector before launching/building WDA. Try to run `./Scripts/bootstrap.sh`

**Comment by toejough** [comment]
Nuts.  Sorry, I thought that appium was running that script for me.

When I run it, I get:
```
./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

sh: webpack: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-driver-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-driver-inspector
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web-driver-inspector
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/npm-debug.log
Error occured during 'npm run build', please check npm build log
```

So... I need webpack?  Or I need to npm install the Inspector... or both... So I tried all three combinations, and every time I got:

```
./Scripts/bootstrap.sh                                                                                                                                                                                                                                                                                                                                                                                                    [3/25299]
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

Hash: 9ed7d0b85cc08341fd0f
Version: webpack 1.13.2
Time: 80ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (59:4)
    at Parser.pp$4.raise (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$3.parseMethod (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2075:10)
    at Parser.pp$1.parseClassMethod (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1137:25)
    at Parser.pp$1.parseClass (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1118:14)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:697:19)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/usr/local/lib/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ multi main
Done
```

The file/location the error occurred looks like:
![screen shot 2016-10-06 at 8 01 54 am](https://cloud.githubusercontent.com/assets/5317312/19151703/29fccb6c-8b9c-11e6-8e1f-3c6aa399a714.png)

So I thought maybe I'd just upgrade to the latest version from github instead of using the packaged submodule from Appium, and when I use that and run ./Scripts/bootstrap.sh I get:

```
> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

(node:92331) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Hash: 9ed7d0b85cc08341fd0f
Version: webpack 1.12.2
Time: 41ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Line 10: Unexpected token
You may need an appropriate loader to handle this file type.
|  */
|
| import React from 'react';
|
| import HTTP from 'js/http';
 @ multi main
Done
```

From poking around it looks like maybe these are both webpack/babel/cli misconfig, but I'm not sure where to go from there.

**Comment by toejough** [comment]
quick edit - the `>` symbols in my file screenshot above are not really there - that's just vim indicating that there are tabs instead of spaces there.  I tried replacing them with spaces just for kicks, but that didn't change anything - the error is about parsing the first `<`, I think.

**Comment by marekcirkos** [comment]
Can you try fetching WDA directly?

**Comment by toejough** [comment]
What do you mean?  I did a git clone of master and that's what the last error output is from.  I cloned it to the same location as the appium install put it...does that matter?  I'll try just cloning outside of the appium dirs.

**Comment by marekcirkos** [comment]
In general we depend on npm to build inspector. Maybe you are missing something in npm or have old version?

**Comment by toejough** [comment]
well shoot, that built (installing WDA on its own, outside of the appium node modules directory, and then running ./Script/bootstrap.sh).  I guess I need to open a ticket with appium.  Thanks for your help!

**Comment by toejough** [comment]
more concretely, what worked for me:

```
cd ~/"${REPOS}"
git clone https://github.com/facebook/WebDriverAgent.git
cd WebDriverAgent
./Scripts/bootstrap.sh
cd "${APPIUM}"
rm -rf WebDriverAgent
ln ~/"${REPOS}"/WebDriverAgent .
```

`REPOS` is literally just a top-level dir named "repos" in my environment, it could be anywhere not inside the appium project.

`APPIUM` is `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver` for me.

I then proceeded to use appium as usual, and it both launched the simulator as expected, and `localhost:8100/inspector` works as advertised (though the appium inspector still complains about not being able to list sessions).

**Comment by ShlOle** [comment]
I had a similar problem. I decided by setting the previous stable version apium.
