### ISSUE TITLE
bootstrap.sh fails with "Not able to find module" error message

### ISSUE THREAD

**Issue by slysid** [facebook/WebDriverAgent#350]
Hi,
I am following instructions to install webdriveragent and running command "./Scripts/bootstrap.sh" and I am getting error message as below

```
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /Users/Bharath/Work/Appium/WebDriverAgent-master/Inspector
> webpack --progress --colors

module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/Bharath/Work/Appium/WebDriverAgent-master/Inspector/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-driver-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-driver-inspector
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web-driver-inspector
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Bharath/Work/Appium/WebDriverAgent-master/Inspector/npm-debug.log
Error occured during 'npm run build', please check npm build log
```
I am running the script on OS X 10.12.1 (macOS Sierra)

**Comment by drptbl** [comment]
Switch yours node from current (7) to LTS (6.9.1) and your issue will not exist.

**Comment by slysid** [comment]
The solution worked

**Comment by marekcirkos** [comment]
You can also run `npm install` in Inspector dictionar.

**Comment by drptbl** [comment]
@marekcirkos but this throws exactly the same error as above.

**Comment by marekcirkos** [comment]
brr. I meant `npm update` ;)

**Comment by marekcirkos** [comment]
brr. I meant `npm update` ;)

**Comment by marekcirkos** [comment]
brr. I meant `npm update` ;)

**Comment by marekcirkos** [comment]
brr. I meant `npm update` ;)
