### ISSUE TITLE
Application crashes when performing a rotate to Landscape

### ISSUE THREAD

**Issue by vjmaiky** [facebook/WebDriverAgent#455]
Ok so i have my setup (newest WDA, appium 1.6.3, Xcode 8.2, iPhone 6= with 10.2).
Everything works until i change orientation to landscape.

AppiumDriverInstance.getInstance().rotate(ScreenOrientation.LANDSCAPE);

rotate is using public class from AppiumDriver.class.

I know that was a problem few weeks ago, but now i read that some managed to do it and some no.

Questions:
Is this fixed or not? Official source please
If yeas, how can i make it run?
If not, when it will be fixed?

Thanks

**Comment by marekcirkos** [comment]
@vjmaiky Do you mean test application crashes or WDA crashes?

**Comment by vjmaiky** [comment]
2017-01-18 14:08:16 INFO  IosAutomationTestWatcher:182 - Test failed with exception:
org.openqa.selenium.WebDriverException: Unable To Rotate Device
Command duration or timeout: 5.54 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'admins-Mac-mini.local', ip: '172.16.102.25', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/Shared/Appium/VTU-Universal.ipa, rotatable=true, networkConnectionEnabled=false, databaseEnabled=false, deviceName=Ioan’s iPhone (10.0.2) [90fbc0d9d9e4792dc70b2e40dcdb2afd91655bfd], fullReset=true, platform=MAC, appium-version=1.6.3, newCommandTimeout=600, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, platformVersion=10.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, waitForAppScript=$.delay(1000); $.acceptAlert();, javascriptEnabled=true, platformName=iOS, udid=90fbc0d9d9e4792dc70b2e40dcdb2afd91655bfd}]
Session ID: 87dde5f7-5ed7-40b3-8768-5850b7aeb0cd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.rotate(AppiumDriver.java:571)
	at dt.emma.ios.phone.SmokeTest_2LoginTest.firstTimeView(SmokeTest_2LoginTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at dt.emma.ios.utils.IosAutomationTestWatcher.evaluateTest(IosAutomationTestWatcher.java:146)
	at dt.emma.ios.utils.IosAutomationTestWatcher.iosevaluate(IosAutomationTestWatcher.java:83)
	at dt.emma.ios.utils.IosAutomationTestWatcher.access$3(IosAutomationTestWatcher.java:80)
	at dt.emma.ios.utils.IosAutomationTestWatcher$1.evaluate(IosAutomationTestWatcher.java:63)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Jan 18, 2017 2:08:17 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

**Comment by vjmaiky** [comment]
Appium Log:

[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/C9025725-598B-4BC7-9A77-28E61DDD32EA/element] with body: {"using":"name","value":"“Telekom Mail” Would Like to Send You Notifications"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"name","value":"“Telekom Mail” Would Like to Send You Notifications","description":"unable to find an element"},"sessionId":"C9025725-598B-4BC7-9A77-28E61DDD32EA","status":7}
[HTTP] <-- POST /wd/hub/session/d2eea2db-2915-456e-92b0-47d574a6ddbc/element 500 10807 ms - 164 
[HTTP] --> POST /wd/hub/session/d2eea2db-2915-456e-92b0-47d574a6ddbc/orientation {"orientation":"LANDSCAPE"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/d2eea2db-2915-456e-92b0-47d574a6ddbc/orientation] to [POST http://localhost:8100/session/C9025725-598B-4BC7-9A77-28E61DDD32EA/orientation] with body: {"orientation":"LANDSCAPE"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unable To Rotate Device","sessionId":"C9025725-598B-4BC7-9A77-28E61DDD32EA","status":777}
[JSONWP Proxy] Replacing sessionId C9025725-598B-4BC7-9A77-28E61DDD32EA with d2eea2db-2915-456e-92b0-47d574a6ddbc
[HTTP] <-- POST /wd/hub/session/d2eea2db-2915-456e-92b0-47d574a6ddbc/orientation 200 5433 ms - 99 
[HTTP] --> POST /wd/hub/session/d2eea2db-2915-456e-92b0-47d574a6ddbc/element {"using":"id","value":"Nicht teilnehmen"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Nicht teilnehmen","d2eea2db-2915-456e-92b0-47d574a6ddbc"]

**Comment by mykola-mokhnach** [comment]
@vjmaiky  I'd recommend to check the device log. It's most likely a crash in the application under test.

**Comment by vjmaiky** [comment]
Indeed. If the screen/view is set/meant to run only in portrait on phone (ex login for page), test run crashes.
If i skip login (i do it in portrait) and only after that i change orientation and continue the test in landscape, works as expected.

**Comment by marekcirkos** [comment]
@vjmaiky  So this is app issue then?

**Comment by vjmaiky** [comment]
As far as i can see yes; if i do the rotate in a screen that by default supports landscape it is working. If i do it in a screen that does not support landscape by default app crashes. I made a workaround with a try catch  (for error "unable to rotate") because i need to run tests in landscape also, and i cannot somehow split tests. Now the problem that i`m facing is that clicks in landscape does not work. I read on many issues/posts that is still a open problem...i commented out for the moment landscape part...

**Comment by marekcirkos** [comment]
@vjmaiky Closing this one as we have task for tracing taps in landscape
