### ISSUE TITLE
No "eslint-config-appium" error while bootstrap.sh executing

### ISSUE THREAD

**Issue by hepilt** [facebook/WebDriverAgent#492]
Got this error everytime when I try to build WDA using bootstrap.sh
How can I fix it?

Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
Error: Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:478:25)
    at load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:495:26)
    at configExtends.reduceRight (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:259:26)

**Comment by marekcirkos** [comment]
This is appium issue. Please raise this issue there.

**Comment by hepilt** [comment]
@marekcirkos are you sure? I'm trying to build WDA, appium seems not use eslint package

**Comment by marekcirkos** [comment]
It tired to reference `eslint-config-appium`, which we do not reference inside WDA.
