### ISSUE TITLE
报了个这个错误，启动时候弹出，是安装的问题么,手动创建这个文件夹也不行，安装是sudo装的

### ISSUE THREAD

**Issue by TesterQiao** [facebook/WebDriverAgent#550]
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/app-inspector/.temp'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:794:18)
      at Object.sync [as mkdir] (/usr/local/lib/node_modules/app-inspector/node_modules/.0.5.1@mkdirp/index.js:71:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:55:5)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

**Comment by codeskyblue** [comment]
Better use English

**Comment by mykola-mokhnach** [comment]
@TesterQiao let me guess without knowing Chinese

```bash
sudo chown -R $USER /usr/local
```

**Comment by marekcirkos** [comment]
@TesterQiao Did it help?
