### ISSUE TITLE
Cannot find module 'eslint-config-appium'

### ISSUE THREAD

**Issue by Azuer** [facebook/WebDriverAgent#558]
Hi!
When I run ./Scripts/bootstrap.sh with command  "sh ./Scripts/bootstrap.sh", errors occured as follow:
-> WebDriverAgent sh ./Scripts/bootstrap.sh   
-e Fetching dependencies
-e Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
**npm WARN web-driver-inspector@1.0.0 No repository field.
Validating Inspector
No errors!
Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/.eslintrc**
Error: Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight.e (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.28.2@appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:260:26)

**Comment by marekcirkos** [comment]
This is definitely Appium issue. We do not use `eslint-config-appium`

**Comment by jlipps** [comment]
@Azuer you shouldn't need to run that command manually, but if you do you should pass `-d` so it doesn't try to build the inspector.

**Comment by Azuer** [comment]
Thanks for reply.
