### ISSUE TITLE
An attempt was made to operate on a modal dialog when one was not open

### ISSUE THREAD

**Issue by derunewige** [facebook/WebDriverAgent#857]
Hello

Today I updated from Appium 1.7.1 to 1.7.2 and now I can't handle Alerts anymore.

```
	public void waitForCrashDialogAndSendIt(long timeout) {
		LOG.debug("Check if crash dialog is present after {} seconds and send it", timeout);
		Wait<AppiumDriver<MobileElement>> wait = new FluentWait<>(this.appiumDriver)
				.withTimeout(timeout, TimeUnit.SECONDS)
				.pollingEvery(POLL_INTERVAL, TimeUnit.MILLISECONDS)
				.ignoring(NoSuchElementException.class, StaleElementReferenceException.class);

		Alert alert;
		try {
			alert = wait.until(ExpectedConditions.alertIsPresent());
			if (alert.getText().contains(IOS_CRASHDIALOG_STRING)) {
				this.findElementInternal(new AppiumObjectLocator(RecognitionStrategy.ACCESSIBILITY, "Immer senden")).click();
				LOG.warn("App crashed in previous run. Crash dialog sent.");
			}
		} catch (TimeoutException e) {
			LOG.debug("Crash dialog was not present after {} seconds", timeout, e);
		} catch (WebDriverException e) {
			LOG.warn("Could not determine the presence of the crash dialog after {} seconds", timeout, e);
			throw ExceptionHandler.handleException(e);
		}
	}
```

The wait condition always throws following error
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An attempt was made to operate on a modal dialog when one was not open.`

Appium log excerpt:
```
2018-01-23 14:48:09:599 - [debug] [MJSONWP] Calling AppiumDriver.getAlertText() with args: ["88dcc853-f42b-4f6a-b44c-b4bcc1559044"]
2018-01-23 14:48:09:602 - [debug] [XCUITest] Executing command 'getAlertText'
2018-01-23 14:48:09:611 - [debug] [JSONWP Proxy] Proxying [GET /alert/text] to [GET http://localhost:8100/session/B95FBDEF-38B2-4AC2-8193-A58194AACD2E/alert/text] with no body
2018-01-23 14:48:09:766 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"B95FBDEF-38B2-4AC2-8193-A58194AACD2E\",\n  \"status\" : 27\n}"
2018-01-23 14:48:09:767 - [MJSONWP] Encountered internal error running command: Error: An attempt was made to operate on a modal dialog when one was not open.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
2018-01-23 14:48:09:769 - [HTTP] <-- GET /wd/hub/session/88dcc853-f42b-4f6a-b44c-b4bcc1559044/alert_text 500 177 ms - 242 
```

Actually, there is really no modal dialog/alert present. Yet. I have a wait condition, because there will appear one. But the exception is already thrown after the first "ping" of the wait condition. 

Probably related to this appium issue: [https://github.com/appium/appium/issues/9544](url)
or rather this post: [https://github.com/appium/appium/issues/9544#issuecomment-352906615](url)

**Comment by marekcirkos** [comment]
From the logs I would say this is expected. 
- Appium checks for alert
- WDA repsonds with 27 which is alert is not present
- Appium raises an error.

What you are saying, this matches the reality, so the problem is on Appiums side.

**Comment by AnuNew** [comment]
I have appium 1.8.1 and facing the same issue in which not able to handle alters.
Please suggest.
