### ISSUE TITLE
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by snowshoes** [facebook/WebDriverAgent#894]
## Expected Behavior

`./Scripts/bootstrap.sh` should pass without errors

### [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.

```bash
⇒  ./Scripts/bootstrap.sh
Fetching dependencies
*** Please update to the latest Carthage version: 0.29.0. You currently are on 0.20.1
*** Cloning RoutingHTTPServer
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** xcodebuild output can be found in /var/folders/02/k64xrs8n5rzd2bzxr9y88_7r0000gn/T/carthage-xcodebuild.C6fOz4.log
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated css-list@0.1.3: Deprecated.

> fsevents@1.1.3 install /Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/fsevents
> node install

[fsevents] Success: "/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN web-driver-inspector@1.0.0 No repository field.

added 686 packages in 19.277s
Validating Inspector
Launching Flow server for /Users/xxx/developer/github/WebDriverAgent/Inspector
Spawned flow server (pid=18140)
Logs will go to /private/tmp/flow/zSUserszSxxxzSdeveloperzSgithubzSWebDriverAgentzSInspector.log
No errors!
ImportDeclaration should appear when the mode is ES6 and in the module context.
AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Program (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/esrecurse/esrecurse.js:104:34)
    at Object.analyze (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/eslint/lib/eslint.js:892:35)
    at processText (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/eslint/lib/cli-engine.js:264:31)
    at processFile (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/Users/xxx/developer/github/WebDriverAgent/Inspector/node_modules/eslint/lib/cli-engine.js:672:25)
```

## Possible Solution

May be `${ROOT}/Inspector/.eslintrc` should be modified

Follow this [issue](https://github.com/eslint/eslint/issues/4344) in eslint, **the problem has been resolved.**

## Steps to Reproduce

1. git clone <url>
2. cd WebDriverAgent
3. ./Script/bootstrap.sh

## Context (Environment)
Mac OS X El Capitan
node v9.3.0
npm v5.5.1
Xcode v8.3
Carthage v0.20.1

**Comment by flasco** [comment]
it can be fixed by upgrade eslint version from "3.13.1" to "5.x.x"
